<div class="">
	<div class="page-title">
		<div class="title_left">
			<h3>About</h3>
		</div>
	</div>

<div class="clearfix"></div>

<div class="row">
	<!-- More Information -->
	<div class="col-md-4 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2><i class="fa fa-info-circle"></i> More Information</h2>
				<ul class="nav navbar-right panel_toolbox">
			  		<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
			  		<li><a class="close-link"><i class="fa fa-times"></i></a></li>
				</ul>
				<div class="clearfix"></div>
			</div>
			<p> Crown Node Manager is a visualisation and control 
				tool for a Crown Platform node.</p>
			<p> Feedback is encouraged at Discord
				<div class="x_content">
					<a href="https://discord.gg/x9UwUTg" target="_blank"><i class="fab fa-discord fa-4x col-md-2 col-xs-3"></i></a>
				</div>
			</p>
			<p> Code contributions are welcome at Github
				<div class="x_content">
					<a href="https://github.com/walkjivefly/crown-node-manager" target="_blank"><i class="fab fa-github fa-4x github-hover col-md-2 col-xs-3"></i></a>
				</div>
			</p>
		</div>
	</div>
	<!-- End More information -->

	<!-- Used software -->
	<div class="col-md-4 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2><i class="fab fa-html5"></i> Used software <small></small></h2>
				<ul class="nav navbar-right panel_toolbox">
			 		<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
			  		<li><a class="close-link"><i class="fa fa-times"></i></a></li>
				</ul>
			<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<h4>Template </h4>
				<ul>
					<li><a href="https://colorlib.com" target="_blank">Gentelella Theme</a></li>
					<li><a href="https://getbootstrap.com" target="_blank">Bootstrap</a></li>
					<li><a href="https://fontawesome.com" target="_blank">Font Awesome</a></li>
					<li><a href="https://www.gosquared.com/" target="_blank">Flags</a></li>
				</ul>
			  
				<h4>Javascript Libaries </h4>
				<ul>
					<li><a href="https://jquery.com" target="_blank">jQuery</a></li>
					<li><a href="https://chartjs.org" target="_blank">Charts.js</a></li>
					<li><a href="https://datatables.net" target="_blank">dataTables</a></li>
					<li><a href="https://jvectormap.com" target="_blank">jVectorMap</a></li>
					<li><a href="https://abpetkov.github.io/switchery/" target="_blank">Switchery</a></li>
					<li><a href="https://chartjs.org" target="_blank">Charts.js</a></li>	
					<li><a href="https://github.com/davidstutz/bootstrap-multiselect" target="_blank">Bootstrap Multiselect</a></li>					 
				</ul> 
				
				<h4>PHP Libaries </h4>
				<ul>
					<li><a href="mailto:sergio@inservibile.org" target="_blank">JSON-RPC PHP</a></li>					   
				</ul> 
			</div>
		</div>
	</div>
	<!-- End used software -->
	<!-- Donations -->
	<div class="col-md-4 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2><i class="fas fa-crown black"></i> Donations</h2>
				<ul class="nav navbar-right panel_toolbox">
	  				<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
	  				<li><a class="close-link"><i class="fa fa-times"></i></a></li>
				</ul>
				<div class="clearfix"></div>
			</div>
			<p> If you find the Crown Node Manager useful please make a donation to 
				<a href="https://iquidus-01.crownplatform.com/address/CRWTo9YAXM1gg3hSqs61T9AmHiia1jWFtfWn" target="_blank"> CRWTo9YAXM1gg3hSqs61T9AmHiia1jWFtfWn </a>
			</p>
		</div>
	</div>
	<!-- End Donations -->
	<!-- Acknowledgements -->
	<div class="col-md-4 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2><i class="fas fa-crown black"></i> Acknowledgments</h2>
				<ul class="nav navbar-right panel_toolbox">
	  				<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
	  				<li><a class="close-link"><i class="fa fa-times"></i></a></li>
				</ul>
				<div class="clearfix"></div>
			</div>
			<p> Forked from <a href="https://github.com/Mirobit/bitcoin-node-manager" target="_blank">Bitcoin Node Manager</a>
			</p>
		</div>
	</div>
	<!-- End Donations -->
</div>
<!-- End Row-->

</div>
</div>
<!-- /page content -->

<!-- footer content -->
<?php include('views/footer.phtml') ?>
<!-- /footer content -->

</div>
</div>

<!-- jQuery -->
<script src="vendors/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="vendors/bootstrap/dist/assets/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="vendors/nprogress/nprogress.js"></script>
<!-- iCheck -->
<script src="vendors/iCheck/icheck.min.js"></script>
<!-- bootstrap-daterangepicker -->
<script src="vendors/moment/min/moment.min.js"></script>
<script src="vendors/jquery.hotkeys/jquery.hotkeys.js"></script>
<script src="vendors/google-code-prettify/src/prettify.js"></script>
<!-- Switchery -->
<script src="vendors/switchery/dist/switchery.min.js"></script>


<!-- Custom Theme Scripts -->
<script src="assets/js/custom.min.js"></script>


</body>
</html>
