		  <!-- Top Info Bar -->
		 <div class="panel panel-default">  
			<div class="panel-body">
				<div class="row tile_count">
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count" style="width:20%;">
					  <span class="count_top"><i class="fa fa-cubes"></i> Total Blocks</span>
					  <div class="count"><?= $content["numberOfBlocks"] ?></div>
					  <span class="count_bottom"><span><?= $content["timeframe"] ?> </span> h timeframe</span>
					</div>
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count" style="width:20%;">
					  <span class="count_top"><i class="fas fa-cloud-download-alt" style="color:lightgreen;"></i> Last Block</span>
					  <div class="count"><?= array_keys($content["blocks"])[count($content["blocks"])-1] ?></div>
					  <span class="count_bottom"><span style="color:lightgreen;"><?= reset($content["blocks"])["timeago"] ?></span> m ago</span>
					</div>
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count" style="width:20%;">
					  <span class="count_top"><i class="fa fa-database"></i> Size</span>
					  <div class="count"><?= $content["totalSize"] ?> <small>MB</small></div>
					  <span class="count_bottom"><span><?= $content["avgSize"] ?> </span> KB avg. block size</span>
					</div>
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count" style="width:20%;">
					  <span class="count_top"><i class="fas fa-crown" style="color:orange;"></i> Total Fees</span>
					  <div class="count"><?= $content["totalFees"] ?> <small>CRW</small></div>
					  <span class="count_bottom"><span class="orange" ><?= $content["avgFee"] ?></span> avg. fees per block</span>
					</div>
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count" style="width:20%;">
					  <span class="count_top"><i class="fas fa-chart-line" style="color:lightblue;"></i> Transactions</span>
					  <div class="count"><?= number_format($content["totalTx"]) ?></div>
					  <span class="count_bottom"><span style="color:lightblue;" ><?= $content["avgTxSize"] ?></span> KB avg. TX size</span>
					</div>
				  </div>
				  </div>
			 </div>
			<!-- Top Info Bar End-->
			<div class="clearfix"></div>
			<?php if(!empty($error) OR !empty($message)){ ?>
			<div class="col-md-3 col-sm-3 col-xs-12">
				<?php if(!empty($error)){ ?> <div class="alert alert-danger" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<?= $error ?> </div><?php }
				if(!empty($message)){ ?> <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<?= $message ?> </div><?php } ?>
			</div>  
			<?php } ?>
			<!-- Content -->				   
			<div class="row">
			
			<!-- Block List -->
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2>Blocks <small>Received</small></h2>
						<ul class="nav navbar-right panel_toolbox">
					  		<li><a class="close-link"><i class="fa fa-times"></i></a></li>
					  		<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
						</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content">

					<table id="receivedblocks" class="table table-striped table-bordered table-valign">
						<thead>
							<tr>
								<th>ID</th>
								<th>Hash</th>
								<th>Time</th>
								<th>Size <span style="font-weight:normal;">(KB)</span></th>
								<th>Fees</th>
								<th>Txns</th>
								<th style="width:70px;">Info</th>
							</tr>
						</thead>

						<tbody>
						<?php $i = 0;
							  foreach($content['blocks']  as $key => $block){ ?>
									<tr>
										<td><?= $key ?></td>
										<td><?= $block["hash"] ?></td> 
										<td><?= $block["time"] ?> <small>(<?= $block["timeago"] ?> m ago)</small></td>  
										<td><?= $block["size"] ?></td>
										<td><?= $block["fees"] ?></td>  	
										<td><?= $block["txcount"] ?></td>
										<td>																					  
											<div class="btn-group pull-left" style="padding:5px 0 3px 7px; margin-bottom:0px">
												<button type="button" class="btn btn-default btn-xs">Explore</button>
												<button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
													<span class="caret"></span>
													<span class="sr-only">Toggle Dropdown</span>
											</button>
											<ul class="dropdown-menu">
												<li><a href="https://iquidus-01.crownplatform.com/block/<?= $block["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Iquidus</a></li>
												<li><a href="https://insight-02.crownplatform.com/block/<?= $block["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Insight</a></li>
												<li><a href="https://chainz.cryptoid.info/crw/block.dws?<?= $block["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Chainz</a></li>
												<li><a href="http://xmn01:3001/block/<?= $block["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Testnet</a></li>
											   </ul>
											</div>										   
								   		</td>										   
									</tr>
						<?php } ?>						
						</tbody>
					</table>
				</div>
				<div class="clearfix"></div>
				</div>
			  </div>
		  </div>
		</div>
	  </div>
	</div>
	<!-- /page content -->

	<!-- footer content -->
	<?php include('views/footer.phtml') ?>
	<!-- /footer content -->
	</div>
	</div>

	<!-- jQuery -->
	<script src="assets/js/jquery.min.js"></script>
	<!-- Bootstrap -->
	<script src="assets/js/bootstrap.min.js"></script>
	<!-- Datatables -->
	<script src="assets/js/jquery.dataTables.min.js"></script>
	<script src="assets/js/dataTables.bootstrap.min.js"></script>
	<script src="assets/js/responsive.bootstrap.js"></script>

	<!-- Custom Theme Scripts -->
	<script src="assets/js/custom.min.js"></script>

	<!-- Datatables -->
	<script>
	  $(document).ready(function() {
		
		 $('#receivedblocks').DataTable( {
			"order": [[ 0, "desc" ]],
			"paging":   false,
			"bInfo": false
		} );
		
	  });
	</script>
	<!-- /Datatables -->
  </body>
</html>
