		<!-- Top Info Bar -->
		<div class="panel panel-default">  
			<div class="panel-body">
				<div class="row tile_count">
					<div class="col-md-3 col-sm-6 col-xs-12 tile_stats_count">
					  <span class="count_top"><i class="fas fa-folder-open"></i> CRW cards</span>
					  <div class="count"><?= $content['nftCount'] ?> <small> Registered</small></div>
					  <span class="count_bottom"><a href="https://crwcards.com" target="_blank"> Learn more about Crown Cards here</a></span>
					</div>
				</div>
			</div>
		</div>
		<!-- Top Info Bar End-->
		<div class="clearfix"></div>
		<div class="row">
			<div class="col-md-3 col-sm-3 col-xs-12">
				<?php if(!empty($error)){ ?> <div class="alert alert-danger" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<?= $error ?> </div><?php }
				if(!empty($message)){ ?> <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<?= $message ?> </div><?php } ?>
			</div>  
		</div>

		<!-- Content -->				   
		<div class="row">
			<!-- NFTs list -->
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2>CRW Card tokens<small> (showing <?=$content['request'] ?>)</small></h2>
						<ul class="nav navbar-right panel_toolbox">
							<li><a class="close-link"><i class="fa fa-times"></i></a>
							<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
						</ul>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<table id="nfts" class="table table-striped table-bordered table-valign">
							<thead>
								<tr>
							 		<th>Username</th>
							 		<th>Tier</th>
							 		<th>Type</th>
									<th>Timestamp</th>
							 		<th>Wallet Address</th>
							 		<!-- <th>Version</th>
							 		<th>Active</th> -->
									<th style="width:70px;">Info</th>
								</tr>
					  		</thead>
							<tbody>
								<?php $i = 0;
							  		foreach($content['nftokens'] as $token){ ?>
									<tr>
										<td><?=$token['cccUsername'] ?></td>
										<td><?=$token['cccTier'] ?></td>
										<td><?=$token['cccType'] ?></td>
										<td><?=$token['timestamp'] ?></td>
										<td><?=$token['cccWalletAddress'] ?></td>
										<!-- <td><?=$token['cccVersion'] ?></td>
										<td><?=$token['cccActive'] ?></td> -->
										<td>										   
											<div class="btn-group pull-right" style="padding:5px 0 3px 0px; margin-bottom:0px">
												<button type="button" class="btn btn-default btn-xs">Info</button>
												<button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
													<span class="caret"></span>
													<span class="sr-only">Toggle Dropdown</span>
												</button>
												<ul class="dropdown-menu">
													<li><a href="https://iquidus-01.crownplatform.com/api/getrawtransaction?txid=<?= $token['registrationTxHash']?>&decrypt=1" target="_blank"> Txn details</a></li>
													<li class="divider"></li>
													<li><a href="https://iquidus-01.crownplatform.com/tx/<?= $token['registrationTxHash'] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Iquidus</a></li>
													<li><a href="https://insight-02.crownplatform.com/tx/<?= $token['registrationTxHash'] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Insight</a></li>
													<li><a href="https://chainz.cryptoid.info/crw/tx.dws?<?= $token['registrationTxHash'] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Chainz</a></li>
												</ul>
											</div>										   
								   		</td>										   
									</tr>
								<?php } ?>						
							</tbody>
						</table>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<!-- /page content -->

		<!-- footer content -->
		<?php include('views/footer.phtml') ?>
		<!-- /footer content -->

		<!-- jQuery -->
		<script src="assets/js/jquery.min.js"></script>
		<!-- Bootstrap -->
		<script src="assets/js/bootstrap.min.js"></script>
		<!-- Datatables -->
		<script src="assets/js/jquery.dataTables.min.js"></script>
		<script src="assets/js/dataTables.bootstrap.min.js"></script>
		<script src="assets/js/dataTables.buttons.min.js"></script>
		<script src="assets/js/responsive.bootstrap.js"></script>

		<!-- Custom Theme Scripts -->
		<script src="assets/js/custom.min.js"></script>

		<!-- Datatables -->
		<script>
	 		$(document).ready(function() {
			$('#nfts').DataTable( {
				"paging": true,
				"bInfo": false,
				"order": [[ 3, "desc" ]]
			} );		
	  		});
		</script>
		<!-- /Datatables -->

  	</body>
</html>