<footer>
<div class="pull-right">
<i class="fas fa-crown black"></i> <a href="https://github.com/walkjivefly/crown-node-manager"> Node Manager v0.1.0</a> - © 2020
</div>
<div class="clearfix"></div>
</footer>
<script>
	<?php
	if($this->section === "main"){
		$section = "";
	}else{
		$section = "?p=".$this->section;
	}
	?>
	window.history.pushState("", "", "<?= $section ?>");
</script>