<!-- Top Info Bar -->
		<div class="panel panel-default">  
			<div class="panel-body">
				<div class="row tile_count">
					<div class="col-md-3 col-sm-4 col-xs-4 tile_stats_count">
					  <span class="count_top"><i class="fa fa-code-branch"></i> Shown Forks</span>
					  <div class="count"><?= $content["forkCount"] ?></div>
					  <span class="count_bottom">in last <?= $content["timeframe"] ?> hours</span>
					</div>
					<div class="col-md-3 col-sm-4 col-xs-4 tile_stats_count">
					  <span class="count_top"><i class="fa fa-code-branch"></i> Forks</span>
					  <div class="count"><?= $content["recentForks"] ?> </div>
					  <span class="count_bottom">in last 24 hours</span>
					</div>
					<div class="col-md-3 col-sm-4 col-xs-4 tile_stats_count">
					  <span class="count_top"><i class="fa fa-code-branch" style="color:orange;"></i> Last Fork</span>
					  <div class="count"><?= $content["blocks"][1]['height'] ?></div>
					  <span class="count_bottom"><span><?= $content["blocks"][1]['timeago'] ?></span> hours ago</span>
					</div>
					<div class="col-md-3 col-sm-4 col-xs-4 tile_stats_count">
					  <span class="count_top"><i class="fa fa-code-branch" style="color:lightgreen;"></i> Last Block Main Chain</span>
					  <div class="count"><?= $content["blocks"][0]['height'] ?></div>
					  <span class="count_bottom"><span><?= $content["blocks"][0]['timeago'] ?></span> hours ago</span>
					</div>
				</div>
			</div>
		</div>
		<!-- Top Info Bar End-->
		<div class="clearfix"></div>
		<?php if(!empty($error) OR !empty($message)){ ?>
		<div class="col-md-3 col-sm-3 col-xs-12">
			<?php if(!empty($error)){ ?> <div class="alert alert-danger" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<?= $error ?> </div><?php }
			if(!empty($message)){ ?> <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<?= $message ?> </div><?php } ?>
		</div>  
		<?php } ?>

		<!-- Content -->				   
		<div class="row">
			
		<!-- Forks List -->
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<h2>Forks <small>Alternative chains / Orphaned blocks</small></h2>
					<ul class="nav navbar-right panel_toolbox">
					  <li><a class="close-link"><i class="fa fa-times"></i></a></li>
					  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content">
					<table id="orhpanedblocks" class="table table-striped table-bordered table-valign">
						<thead>
							<tr>
								<th>ID</th>
								<th>Hash</th>
								<th>Status</th>
								<th>Time</th>
								<th>Length</th>
								<th>Size <span style="font-weight:normal;">(KB)</span></th>
								<th style="width:70px;">Info</th>
							</tr>
						</thead>
						<tbody>
							<?php $i = 0;
								reset($content['blocks']);
								array_shift($content['blocks']);
								foreach($content['blocks'] as $block){ ?>
									<tr>
										<td><?= $block['height'] ?></td>
										<td><?= $block["hash"] ?></td>   
										<td><?= $block["status"] ?></td>
										<td><?= (isset($block["time"])) ? $block["time"]." <small>(".$block["timeago"]." hours ago)</small>"  : "" ?></td>
										<td><?= $block['forklength'] ?></td>
										<td><?= (isset($block["size"])) ? $block["size"] : "" ?></td>	
										<td>																						
											<div class="btn-group pull-left" style="padding:5px 0 3px 7px; margin-bottom:0px">
												<button type="button" class="btn btn-default btn-xs">Details</button>
												<button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
													<span class="caret"></span>
													<span class="sr-only">Toggle Dropdown</span>
											</button>
											<ul class="dropdown-menu">
												<li><a href="https://iquidus-01.crownplatform.com/block/<?= $block["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Iquidus</a></li>
												<li><a href="https://insight-02.crownplatform.com/block/<?= $block["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Insight</a></li>
												<li><a href="https://chainz.cryptoid.info/crw/block.dws?<?= $block["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Chainz</a></li>
												<li><a href="http://xmn01:3001/block/<?= $block["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Testnet</a></li>
 											</ul>
											</div>										   
										</td>										   
									</tr>
							<?php } ?>						
						</tbody>
					</table>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
		</div>
		</div>
	  </div>
	</div>
	<!-- /page content -->

	<!-- footer content -->
	<?php include('views/footer.phtml') ?>
	<!-- /footer content -->

	<!-- jQuery -->
	<script src="assets/js/jquery.min.js"></script>
	<!-- Bootstrap -->
	<script src="assets/js/bootstrap.min.js"></script>
	<!-- Datatables -->
	<script src="assets/js/jquery.dataTables.min.js"></script>
	<script src="assets/js/dataTables.bootstrap.min.js"></script>
	<script src="assets/js/responsive.bootstrap.js"></script>

	<!-- Custom Theme Scripts -->
	<script src="assets/js/custom.min.js"></script>

	<!-- Datatables -->
	<script>
	  $(document).ready(function() {
		
		 $('#orhpanedblocks').DataTable( {
			"order": [[ 0, "desc" ]],
			"paging": true,
			"bInfo": false
		} );
		
	  });
	</script>
	<!-- /Datatables -->
  </body>
</html>