		<!-- Top Info Bar -->
		<div class="panel panel-default">  
			<div class="panel-body">
				<div class="row tile_count">
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count" style="width:15%;">
					  <span class="count_top"><i class="fas fa-sitemap"></i> Masternodes</span>
					  <div class="count"><?= $content['nodeCount'] ?> </div>
					  <span class="count_bottom"> Online </span>
					</div>
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count" style="width:15%;">
					  <span class="count_top"><i class="fas fa-sitemap"></i> </span>
					  <div class="count"><?= $content['EnabledCount'] ?> </div>
					  <span class="count_bottom"> Enabled </span>
					</div>
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count" style="width:70%">
					  <span class="count_top"><i class="fas fa-sitemap"></i> </span>
					  <div class="count" style="font-size:25px"><?= $content['LastWinner'] ?> </div>
					  <span class="count_bottom"> Last winner </span>
					</div>
				</div>
			</div>
		</div>
		<!-- Top Info Bar End-->
		<div class="clearfix"></div>
		<div class="row">
			<div class="col-md-3 col-sm-3 col-xs-12">
				<?php if(!empty($error)){ ?> <div class="alert alert-danger" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<?= $error ?> </div><?php }
				if(!empty($message)){ ?> <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<?= $message ?> </div><?php } ?>
			</div>  
		</div>

		<!-- Content -->				   
		<div class="row">
			<!-- Masternodes list -->
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2>Masternodes<small>Incentivised with 10000 CRW collateral</small></h2>
						<ul class="nav navbar-right panel_toolbox">
							<li><a class="close-link"><i class="fa fa-times"></i></a>
							<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
						</ul>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<table id="nodes" class="table table-striped table-bordered table-valign">
							<thead>
								<tr>
							 		<th>Collateral txid</th>
							 		<th>Status</th>
							 		<th>Protocol</th>
									<th>Collateral address</th>
									<th>IP address</th>
									<th>Last seen</th>
									<th>Time active</th>
									<th>Last paid</th>
								</tr>
					  		</thead>
							<tbody>
								<?php $i = 0;
							  		foreach($content['node'] as $node){ ?>
									<tr>
										<td><?=$node['txid'] ?></td>
										<td><?=$node['status'] ?></td>
										<td><?=$node['protocol'] ?></td>
										<td><?=$node['address'] ?></td>
										<td><?=$node['IP'] ?></td>
										<td><?=$node['lastseen'] ?></td>
										<td><?=$node['activetime'] ?></td>
										<td><?=$node['lastpaid'] ?></td>
										<td>										   
											<div class="btn-group pull-left" style="padding:5px 0 3px 0px; margin-bottom:0px">
												<button type="button" class="btn btn-default btn-xs">Manage</button>
												<button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
													<span class="caret"></span>
													<span class="sr-only">Toggle Dropdown</span>
												</button>
												<ul class="dropdown-menu">
												    <li><a href="https://iquidus-01.crownplatform.com/tx/<?= $node['txid'] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Iquidus</a></li>
													<li><a href="https://insight-02.crownplatform.com/tx/<?= $node['txid'] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Insight</a></li>
													<li><a href="https://chainz.cryptoid.info/crw/tx.dws?<?= $node['txid'] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Chainz</a></li>
													<li><a href="http://xmn01:3001/tx/<?= $node['txid'] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Testnet</a></li>
												</ul>
											</div>										   
								   		</td>										   
									</tr>
								<?php } ?>						
							</tbody>
						</table>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<!-- /page content -->

		<!-- footer content -->
		<?php include('views/footer.phtml') ?>
		<!-- /footer content -->

		<!-- jQuery -->
		<script src="assets/js/jquery.min.js"></script>
		<!-- Bootstrap -->
		<script src="assets/js/bootstrap.min.js"></script>
		<!-- Datatables -->
		<script src="assets/js/jquery.dataTables.min.js"></script>
		<script src="assets/js/dataTables.bootstrap.min.js"></script>
		<script src="assets/js/dataTables.buttons.min.js"></script>
		<script src="assets/js/responsive.bootstrap.js"></script>

		<!-- Custom Theme Scripts -->
		<script src="assets/js/custom.min.js"></script>

		<!-- Datatables -->
		<script>
	 		$(document).ready(function() {
			$('#nodes').DataTable( {
				"paging":   false,
				"bInfo": false,
				"order": [[ 3, "desc" ]]
			} );		
	  		});
		</script>
		<!-- /Datatables -->

  	</body>
</html>