		<!-- Top Info Bar -->
		<div class="panel panel-default">  
			<div class="panel-body">
				<div class="row tile_count">
					<div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
					  <span class="count_top"><i class="fas fa-folder-open"></i> NFT protocols</span>
					  <div class="count"><?= ($content['nftProtosCount']).(($content['nftProtosCount'] != 'N/A') ? "<small> Registered</small>" : "")?></div>
					  <span class="count_bottom"> -</span>
					</div>
					<div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
					  <span class="count_top"><i class="fas fa-qrcode" style="color:#EDDA74;"></i> NFTs count</span>
					  <div class="count"><?= ($content['totalsupply']).(($content['totalsupply'] != 'N/A') ? "<small> Registered</small>" : "")?></div>
					  <span class="count_bottom"><?= ($content['nftCount'] != "N/A" ? $content['nftCount']." Displayed" : "-")?></span>
					</div>
				</div>
			</div>
		</div>
		<!-- Top Info Bar End-->
		<div class="clearfix"></div>
		<div class="row">
			<div class="col-md-3 col-sm-3 col-xs-12">
				<?php if(!empty($error)){ ?> <div class="alert alert-danger" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<?= $error ?> </div><?php }
				if(!empty($message)){ ?> <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<?= $message ?> </div><?php } ?>
			</div>  
		</div>

		<!-- Content -->				   
		<div class="row">
			<!-- NFTs list -->
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2>Non-fungible tokens<small> (showing <?=$content['request'] ?>)</small></h2>
						<ul class="nav navbar-right panel_toolbox">
							<li><a class="close-link"><i class="fa fa-times"></i></a>
							<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
						</ul>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<table id="nfts" class="table table-striped table-bordered table-valign">
							<thead>
								<tr>
							 		<th>Protocol ID</th>
							 		<th>Token ID</th>
							 		<th>Owner</th>
									<th>Timestamp</th>
									<th>Info</th>
								</tr>
					  		</thead>
							<tbody>
								<?php $i = 0;
							  		foreach($content['nftokens'] as $token){ ?>
									<tr>
										<td style="padding-right:0px;"><?=$token['nftProtocolId'] ?></td>
										<td><?=$token['nftId'] ?></td>
										<td><?=$token['nftOwnerKeyId'] ?></td>
										<td><?=$token['timestamp'] ?></td>
										<!-- <td><?=$token['registrationTxHash'] ?></td> -->
										<td>										   
											<div class="btn-group pull-right" style="padding:5px 0 3px 0px; margin-bottom:0px">
												<button type="button" class="btn btn-default btn-xs">Info</button>
												<button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
													<span class="caret"></span>
													<span class="sr-only">Toggle Dropdown</span>
												</button>
												<ul class="dropdown-menu">
													<li><a href="?p=nfts&proto=<?= $token['nftProtocolId'] ?>" target="_self">Same protocol</a></li>
													<li><a href="?p=nfts&owner=<?= $token['nftOwnerKeyId'] ?>" target="_self">Same owner</a></li>
													<li><a href="?p=nfts&proto=<?= $token['nftProtocolId'] ?>&owner=<?= $token['nftOwnerKeyId'] ?>" target="_self">Same protocol and owner</a></li>
												    <li><a href="https://iquidus-01.crownplatform.com/tx/<?= $token['registrationTxHash'] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Iquidus</a></li>
													<li><a href="https://insight-02.crownplatform.com/tx/<?= $token['registrationTxHash'] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Insight</a></li>
													<li><a href="https://chainz.cryptoid.info/crw/tx.dws?<?= $token['registrationTxHash'] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Chainz</a></li>
													<li><a href="http://xmn01:3001/tx/<?= $token['registrationTxHash'] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Testnet</a></li>
												</ul>
											</div>										   
								   		</td>										   
									</tr>
								<?php } ?>						
							</tbody>
						</table>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<!-- /page content -->

		<!-- footer content -->
		<?php include('views/footer.phtml') ?>
		<!-- /footer content -->

		<!-- jQuery -->
		<script src="assets/js/jquery.min.js"></script>
		<!-- Bootstrap -->
		<script src="assets/js/bootstrap.min.js"></script>
		<!-- Datatables -->
		<script src="assets/js/jquery.dataTables.min.js"></script>
		<script src="assets/js/dataTables.bootstrap.min.js"></script>
		<script src="assets/js/dataTables.buttons.min.js"></script>
		<script src="assets/js/responsive.bootstrap.js"></script>

		<!-- Custom Theme Scripts -->
		<script src="assets/js/custom.min.js"></script>

		<!-- Datatables -->
		<script>
	 		$(document).ready(function() {
			$('#nfts').DataTable( {
				"paging": true,
				"bInfo": false,
				"order": [[ 3, "desc" ]]
			} );		
	  		});
		</script>
		<!-- /Datatables -->

  	</body>
</html>