		<!-- Top Info Bar -->
		<div class="panel panel-default">  
			<div class="panel-body">
				<div class="row tile_count">
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
						<span class="count_top"><i class="far fa-paper-plane"></i> Proposals</span>
						<div class="count"><?= $content['pCount'] ?> </div>
						<span class="count_bottom"> Current </span>
					</div>
					<div class="col-md-4 col-sm-4 col-xs-6 tile_stats_count">
						<span class="count_top"><i class="fa fa-cubes"></i> Next superblock</span>
						<div class="count"><?= $content['nextSuperblock'] ?> </div>
						<span class="count_bottom"><small><?=$content['nextDate']?></small></span>
					</div>
					<div class="col-md-2 col-sm-6 col-xs-6 tile_stats_count">
						<span class="count_top"><i class="fas fa-crown"></i> Total Requested </span>
						<div class="count" style="color:<?=$content['reqColour']?>"><?= $content['budgetRequested'] ?> </div>
						<span class="count_bottom"> - </span>
					</div>
					<div class="col-md-2 col-sm-6 col-xs-6 tile_stats_count">
						<span class="count_top"><i class="fas fa-crown"></i> Total Passing </span>
						<div class="count" style="color:<?=$content['passingColour']?>"><?= $content['budgetPassing'] ?> </div>
						<span class="count_bottom"> - </span>
					</div>
					<div class="col-md-2 col-sm-6 col-xs-6 tile_stats_count">
						<span class="count_top"><i class="fas fa-crown"></i> Total Remaining </span>
						<div class="count" style="color:<?=$content['remainingColour']?>"><?= $content['budgetRemaining'] ?> </div>
						<span class="count_bottom"> - </span>
					</div>
				</div>
			</div>
		</div>
		<!-- Top Info Bar End-->
		<div class="clearfix"></div>
		<div class="row">
			<div class="col-md-3 col-sm-3 col-xs-12">
				<?php if(!empty($error)){ ?> <div class="alert alert-danger" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<?= $error ?> </div><?php }
				if(!empty($message)){ ?> <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<?= $message ?> </div><?php } ?>
			</div>  
		</div>

		<!-- Content -->				   
		<div class="row">
			<!-- Proposals list -->
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2>Proposals<small>Crown Decentralised Governance System</small></h2>
						<ul class="nav navbar-right panel_toolbox">
							<li><a class="close-link"><i class="fa fa-times"></i></a></li>
							<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
						</ul>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<table id="proposals" class="table table-striped table-bordered table-valign">
							<thead>
								<tr>
							 		<th>Name</th>
									<th>Passing</th>
							 		<th>First block</th>
							 		<th>Payment Count</th>
									<th>Months Left</th>
									<!-- <th>Payment Address</th> -->
									<th>Monthly Payment</th>
									<th>Total Payment</th>
									<th>Yeas</th>
									<th>Nays</th>
									<th>Abstentions</th>
									<th>Margin</th>
									<th style="width:70px;">Info</th>
								</tr>
					  		</thead>
							<tbody>
								<?php $i = 0;
							  		foreach($content['proposal'] as $proposal){ ?>
									<tr>
										<td><a href="<?=$proposal["URL"]?>" target="_blank"><?=$proposal['name'] ?></a></td>
										<td><?=$proposal['passing'] ?></td>
										<td><?=$proposal['firstBlock'] ?></td>
										<td><?=$proposal['totalPaymentCount'] ?></td>
										<td><?=$proposal['remainingPaymentCount'] ?></td>
										<!-- <td><?=$proposal['paymentAddress'] ?></td> -->
										<td><?=$proposal['monthlyPayment'] ?></td>
										<td><?=$proposal['totalPayment'] ?></td>
										<td><?=$proposal['yeas'] ?></td>
										<td><?=$proposal['nays'] ?></td>
										<td><?=$proposal['abstains'] ?></td>
										<td><?=$proposal['passingMargin'] ?></td>
										<td>										   
											<div class="btn-group pull-left" style="padding:5px 0 3px 0px; margin-bottom:0px">
												<button type="button" class="btn btn-default btn-xs">Explore</button>
												<button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
													<span class="caret"></span>
													<span class="sr-only">Toggle Dropdown</span>
												</button>
												<ul class="dropdown-menu">
												    <li><a href="https://iquidus-01.crownplatform.com/tx/<?= $proposal['hash'] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Iquidus</a></li>
													<li><a href="https://insight-02.crownplatform.com/tx/<?= $proposal['hash'] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Insight</a></li>
													<li><a href="https://chainz.cryptoid.info/crw/tx.dws?<?= $proposal['hash'] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Chainz</a></li>
												</ul>
											</div>										   
								   		</td>										   
									</tr>
								<?php } ?>						
							</tbody>
						</table>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<!-- /page content -->
		</div>

		<!-- footer content -->
		<?php include('views/footer.phtml') ?>
		<!-- /footer content -->
		</div>
		</div>

		<!-- jQuery -->
		<script src="assets/js/jquery.min.js"></script>
		<!-- Bootstrap -->
		<script src="assets/js/bootstrap.min.js"></script>
		<!-- Datatables -->
		<script src="assets/js/jquery.dataTables.min.js"></script>
		<script src="assets/js/dataTables.bootstrap.min.js"></script>
		<script src="assets/js/dataTables.buttons.min.js"></script>
		<script src="assets/js/responsive.bootstrap.js"></script>

		<!-- Custom Theme Scripts -->
		<script src="assets/js/custom.min.js"></script>

		<!-- Datatables -->
		<script>
	 		$(document).ready(function() {
			$('#proposals').DataTable( {
				"paging": true,
				"lengthChange": true,
				"lengthMenu": [ [10, 25, 50, -1], [10, 25, 50, "All"] ],
				"bInfo": false,
				"order": [[ 10, "desc" ]]
			} );		
	  		});
		</script>
		<!-- /Datatables -->

  	</body>
</html>