		<!-- Top Info Bar -->
		<div class="panel panel-default">  
			<div class="panel-body">
				<div class="row tile_count">
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count" style="width:30%;">
					  <span class="count_top"><i class="fas fa-wrench"></i> Sporks</span>
					  <div class="count"><?= $content["SporksCount"] ?><small> Defined</small></div>
					  <span class="count_bottom"><?= $content["SporksEnabled"] ?><small> Enabled</small></span>
					</div>
				</div>
			</div>
		</div>
		<!-- Top Info Bar End-->
		<div class="clearfix"></div>
		<div class="row">
			<div class="col-md-3 col-sm-3 col-xs-12">
				<?php if(!empty($error)){ ?> <div class="alert alert-danger" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<?= $error ?> </div><?php }
				if(!empty($message)){ ?> <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<?= $message ?> </div><?php } ?>
			</div>  
		</div>

		<!-- Content -->				   
		<div class="row">
			<!-- Sporks list -->
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2>Sporks<small> dynamic platform configuration</small></h2>
						<ul class="nav navbar-right panel_toolbox">
							<li><a class="close-link"><i class="fa fa-times"></i></a>
							<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
						</ul>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<table id="sporks" class="table table-striped table-bordered table-valign">
							<thead>
								<tr>
									<th>Key</th>
									<th>Value</th>
							 		<th>Value as timestamp</th>
							 		<th>Status</th>
								</tr>
					  		</thead>
							<tbody>
								<?php foreach($content['sporks'] as $spork){ ?>
									<tr>
										<td style="padding-right:0px;"><?=$spork['name'] ?></td>
										<td><?=$spork['value'] ?></td>
										<td><?=$spork['timestamp'] ?></td>
										<td><?=$spork['status'] ?></td>									   
									</tr>
								<?php } ?>						
							</tbody>
						</table>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<!-- /page content -->

		<!-- footer content -->
		<?php include('views/footer.phtml') ?>
		<!-- /footer content -->

		<!-- jQuery -->
		<script src="assets/js/jquery.min.js"></script>
		<!-- Bootstrap -->
		<script src="assets/js/bootstrap.min.js"></script>
		<!-- Datatables -->
		<script src="assets/js/jquery.dataTables.min.js"></script>
		<script src="assets/js/dataTables.bootstrap.min.js"></script>
		<script src="assets/js/dataTables.buttons.min.js"></script>
		<script src="assets/js/responsive.bootstrap.js"></script>

		<!-- Custom Theme Scripts -->
		<script src="assets/js/custom.min.js"></script>

		<!-- Datatables -->
		<script>
	 		$(document).ready(function() {
			$('#sporks').DataTable( {
				"paging":   false,
				"searching": false,
				"bInfo": false,
				"order": [[ 1, "asc" ]]
			} );		
	  		});
		</script>
		<!-- /Datatables -->

  	</body>
</html>